# Generated by Django 3.2.8 on 2021-10-30 17:03

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=crm.models.customer_image_path
            ),
        ),
    ]
