apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
data:
{{- with .Values.configmap }}
{{- toYaml . | nindent 2 }}
{{- end }}
