apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}-lb
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
  annotations:
    {{ .Values.service_lb.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service_lb.type }}
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service_lb.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
